service: todo

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    TABLE_NAME: todoServerless
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "Fn::GetAtt": [todosTable, Arn]

resources:
  Resources:
    todosTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: userItem
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: userItem
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  todosCreate:
    handler: api/routes/todos/create.handle
    events:
      - http:
          path: user/{userId}/todos
          method: post
          cors: true
          request:
            parameters:
              paths:
                userId: true

  todosGet:
    handler: api/routes/todos/get.handle
    events:
      - http:
          path: user/{userId}/todos
          method: get
          cors: true
          request:
            parameters:
              paths:
                userId: true
      - http:
          path: user/{userId}/todos/{todoId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                userId: true
                todoId: true

  todosDelete:
    handler: api/routes/todos/delete.handle
    events:
      - http:
          path: user/{userId}/todos/{todoId}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                userId: true
                todoId: true

  userCreate:
    handler: api/routes/user/create.handle
    events:
      - http:
          path: user
          method: post
          cors: true

package:
  individually: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: "non-linux"
    usePoetry: true
    pythonBin: /home/gitpod/.pyenv/shims/python
